import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'md.ashrafiftekhar' at '6/6/17 4:49 PM' with Gradle 2.14.1
 *
 * @author md.ashrafiftekhar, @date 6/6/17 4:49 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
