/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'md.ashrafiftekhar' at '6/6/17 4:49 PM' with Gradle 2.14.1
 *
 * @author md.ashrafiftekhar, @date 6/6/17 4:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
