/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'md.ashrafiftekhar' at '5/25/17 11:24 AM' with Gradle 2.14.1
 *
 * @author md.ashrafiftekhar, @date 5/25/17 11:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
